### ISSUE TITLE
Returns floating numbers

### ISSUE THREAD

**Issue by Emeraude** [patrickkettner/filesize-parser#12]
Sometimes it returns floating numbers instead of integers.

```js
var filesizeParser = require('filesize-parser');
filesizeParser('2.1GiB'); // returns 2254857830.4
filesizeParser('2.156KiB'); // returns 2207.744
```
A decimal number of bytes doesn't make any sense, maybe the result could be ceiled ?

**Comment by patrickkettner** [comment]
sounds like a good idea - would you like to PR the change?

**Comment by Emeraude** [comment]
Done with PR #13
